### ISSUE TITLE
how hard to switch objective-c for python2?

### ISSUE THREAD

**Issue by johndpope** [LuizZak/SwiftRewriter#10]
I spat these files out some while back
 https://github.com/johndpope/ANTLR-Swift-Target/tree/master/gen/grammars-v4/python2
 I get that they'd need to be redone with Antlr4-Swift
https://github.com/LuizZak/Antlr4-Swift

I've been dabbling with swift for tensorflow
https://github.com/johndpope/SwiftReinforce

<img width="1130" alt="screen shot 2018-09-18 at 2 58 45 pm" src="https://user-images.githubusercontent.com/289994/45709996-61a9d580-bb53-11e8-9015-4170dc0b496f.png">

which allows import of python code directly into swift / you still need tensorflow toolchain 
https://github.com/johndpope/SwiftReinforce/blob/master/SwiftReinforce/Python/PythonClass.swift

**Comment by LuizZak** [comment]
I foresaw the feasibility of doing Objc2<other> with the current architecture, but not <other>2Swift!

It'd be a bit challenging, I believe. Though first I have to know what kind of code are you looking to convert? Is it snippets, files, or large projects? And how 'pythony' is this code, as far as using specific Python features go?

As outlined in a [little doc describing the Architecture of the library](https://github.com/LuizZak/SwiftRewriter/blob/master/Architecture.md), the ObjC parsing phase is separate from the later transpiling steps, so it could theoretically be done, but in reality there's still quite a bit of coupling between the Obj-C grammar and later phases left, which would make it tricky.

Also, I'm curious how the type resolver system used in later phases would fall in place on top of the dynamic nature of Python.

**Comment by johndpope** [comment]
Just Snippets / camel case vars / rename def / replace #comments -> // comments / insert brackets / if antlr can pick up you need a var declaration all the better. 

I built a converter using objc / chime and regular expressions. At some point / there’s a single file doing multiple crude reflex nasties.
https://github.com/BellGeorge/objc2swift.io


For  alpha version need not be workable. Just needs to look good and be somewhat fixable / appendable going forward.

**Comment by cs-luiz-silva** [comment]
Hmm if the intention is to just shove a Python 'frontend' to the transpiler and have it spit out Swift syntax, I'd venture to say it's totally doable, but only after trying I could say with certainty.

The main bits to change would be `ObjcParserAntlr`, `ObjcParser` and `GrammarModels`. `ObjcParserAntlr` is the one where you'd dump any generated ANTLR recognizer, and `ObjcParser` does the job of taking string source code and invoking ANTLR, producing a customized AST contained within `GrammarModels`.

The ANTLR tree is not touched again until expression parsing done by `SwiftStatementASTReader`: there I use a visitor to convert Objective-C AST into `SwiftAST` `Statement` and `Expression` nodes. This part should be a little easier since you can do it in steps, adding support for more syntax as you go, but changing `ObjcParser` and `ObjcParserAntlr` is going to be non-trivial.

**Comment by LuizZak** [comment]
I'll be closing this issue, for now. If you have any other questions, feel free to open new issues!
